import { type NextPage } from "next";
import Head from "next/head";
import AlbumCard from "../../components/album-card";
import Footer from "../../components/footer";
import Header from "../../components/header";
import { api } from "../../utils/api";

const SearchMusicsPage: NextPage = () => {
	const spotifySearch = api.spotify.getSearch.useQuery({
		searchQuery: "blurry face",
	});
	return (
		<>
			<Head>
				<title>Página de busca</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-gray-900">
				<Header />
				<main className="flex min-h-screen flex-col items-center justify-center">
					<div className=" bg-gray-900">
						<div className="mx-32 mb-8">
							<form className="mb-16">
								<label className="text-left text-lg text-gray-200">
									Busque por artistas, álbuns ou músicas
								</label>
								<input
									type="text"
									placeholder="Clique aqui e comece a escrever..."
									className="h-16 w-full bg-gray-900 p-2 text-left text-5xl font-bold text-gray-200 outline-none focus:border-b-4 focus:border-gray-500"
								/>
							</form>
							<h2 className="text-2xl text-gray-50">
								Álbuns buscados recentemente
							</h2>
						</div>
						<div className=" my-4 flex w-full max-w-full flex-wrap items-center justify-center gap-6 bg-gray-900">
							{spotifySearch.data?.albums?.map((album) => {
								return (
									<AlbumCard key={album.id} album={album} />
								);
							})}
						</div>
					</div>
				</main>
				<Footer />
			</div>
		</>
	);
};

export default SearchMusicsPage;
