import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../../utils/api";

const SearchMusicsPage: NextPage = () => {
	const spotifyPlaylist = api.spotify.getSpotifyPlaylist.useQuery({
		playlistId: "3cEYpjA9oz9GiPac4AsH4n",
	});
	const spotifySearch = api.spotify.getSpotifySearchAlbum.useQuery({
		searchQuery: "blurry face",
	});
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
					<h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
						Create{" "}
						<span className="text-[hsl(280,100%,70%)]">T3</span> App
					</h1>
					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
						<Link
							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
							href="/search-musics"
							target="_self"
						>
							<h3 className="text-2xl font-bold">
								Search musics →
							</h3>
							<div className="text-lg">
								Search musics from Spotify!
							</div>
						</Link>
						<Link
							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
							href="/"
							target="_self"
						>
							<h3 className="text-2xl font-bold">
								Documentation →
							</h3>
							<div className="text-lg">
								Learn more about Create T3 App, the libraries it
								uses, and how to deploy it.
							</div>
						</Link>
					</div>
					<div className="flex flex-col items-center gap-2">
						<p className="text-2xl text-white">
							{/* {spotifyPlaylist.data ? spotifyPlaylist.data.greeting : "Loading tRPC query..."} */}
						</p>
					</div>
				</div>
			</main>
		</>
	);
};

export default SearchMusicsPage;
